# -*- coding: utf-8 -*-
"""Introdução a objetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyasE56n57Y65NYzwTr3HKMhlpDR4cta

#🔨 Introdução aos objetos

Como assim *introdução* se falamos de objetos até agora? É bem isso. O conceito de objetos é um tanto complexo, por isso demanda um capítulo só sobre isso. Mas relaxa, você vai acabar esse notebook entendendo tudo!

# 📖 Explorando valores e referências

Até agora, nós usamos variáveis dos tipos <font color = "orange"><b>`int`</font></b>, <font color = "orange"><b>`float`</font></b>, <font color = "orange"><b>`bool`</font></b>, <font color = "orange"><b>`string`</font></b>, <font color = "orange"><b>`list`</font></b> and <font color = "orange"><b>`tuple`</font></b>. Acontece que alguns desses são tratados como **valores**, enquanto outros são tratados como **referências**.

Para entender o que isso significa e como implica na maneira de programarmos, esse problema vai ajudá-lo a explorar os <font color = "orange"><b>`types`</font></b>.
"""

a = 'python'
b = 'python'

"""Nesse caso, **`a`** e **`b`** referem-se ao mesmo objeto na memória, mais que iguais, **eles são o mesmo objeto**.

Mas como podemos ter certeza disso? Como já fizemos antes, podemos buscar o id de uma variável com a função <font color = "orange"><b>`id()`</b></font>. O Python recebe a variável e retorna o id - seu endereço na memória - do objeto que está atribuído a ela.
"""

print(id(a))
print(id(b))
print(id(a) == id(b))
print(a is b)

"""Então os dois são, de fato, o mesmo. Podemos comparar de uma maneira mais concisa: em Python, temos a palavrinha mágica <font color = "orange"><b>`is`</font></b> que nos diz se duas variáveis são o mesmo objeto ou não."""

a is b

"""Agora, vamos testar o mesmo código acima com algo diferente. Em vez de "python", vamos tentar o número 5, o número 5.0 e o booleano True."""

a = 5
b = 5.0

id(a), id(b)

"""Perceba que o id de **`a`** é diferente do id de **`b`**. Então..."""

a is b

"""...mas"""

a == b

"""Interessante! Então, como regra geral, temos que **objetos de diferentes tipos sempre residem em diferentes endereços na memória**.

Além disso, vimos que <b>`a == b`</b> é <b>`True`</b>, o que faz sentido, já que 5 e 5.0 realmente são equivalentes.

Agora, vamos tentar com <font color = "orange"><b>`listas`</font></b>:
"""

a = [1, 2, 3]
b = [1, 2, 3]

a is b

a == b

"""Perceba que as <font color = "orange"><b>`listas`</b></font> são tratadas diferentemente das outras classes que vimos até agora. Elas são objetos diferentes (por terem ids diferentes), mas, como na matemática, elas são iguais por terem os mesmos elementos. Tá confuso, eu sei! Mas na verdade é bem simples!! As duas <font color = "orange"><b>`listas`</b></font> são iguais, porem não são a mesma coisa. É quase como se elas fossem gêmeas: iguais, mas pessoas diferentes (no nosso caso, em vez de pessoas, objetos!).

Outra maneira de ver isso é a seguinte:
"""

a[1] = 70
print(a) # Mudamos a...

print(b) # ...mas b continuou igual!

# Então temos que:
a == b

"""Mudanças em uma lista não afetam a outra! O que significa realmente que elas não eram a mesma coisa.

Mas e se fizemos diferente:
"""

a = [1, 2, 3]
b = a

"""E mudarmos o primeiro item de b..."""

b[1] = 70

"""...o que será que acontece com a?"""

a

"""Então, se ao mudarmos **`b`**, tivemos **`a`** alterado, temos que:"""

a is b

id(a), id(b)

"""E se mudarmos algo em **`a`**, será que **`b`** muda também?"""

a[1] = 70

print(a)
print(b)
print(a == b)

"""Sim!

Esse conceito é chamado de **aliasing** (vem de *alias* - apelido), onde duas variáveis se referem ao mesmo objeto. Com os <font color = "orange"><b>`types`</b></font> primitivos que vimos acima, Python faz automaticamente a correspondência entre as variáveis se elas tem o mesmo** valor** e **tipo**. Com listas, precisamos explicitar se queremos fazer essa correspondência, igualando as variáveis, em vez de apenas atribuí-las aos mesmos valor e tipo.
"""

a = 1
b = 1
a is b

a = 1
b = a
a is b

id(a), id(b)

a += 1

"""Pode parecer confuso **`b`** não ter devolvido **`2`**, mas faz sentido! **`a`** e **`b`** eram a mesma coisa, mas reatribuímos um valor a **`a`**, o que significa que agora ele é **outro objeto** e tem** outro lugar na memória**."""

id(a), id(b) # Perceba que o id de a mudou, mas o de b continua o mesmo que o anterior.

"""Assim, para que continuemos tendo **`a`==`b`**, precisamos definir de novo isso! Isso porque para **`b`** agora ele é o antigo **`a`**: ele foi associado ao valor de **`a`** quando **`a`** era 1. Depois que **`a`** virou outro objeto, ninguém disse isso pro **`b`**. Mas podemos dizer:"""

b = a
b

a is b

"""# 🔁 Explorando a mutabilidade

Agora é a hora de realmente entender como o computador pensa e trabalha.

**Atribuir** um valor a uma variável significa algo do tipo:
"""

x = 5
y = 'Ola'
z = [1, 2, 3]

"""Modificar uma variável é algo do tipo:"""

z.append('oi')

z

"""Sobrescrever uma variável imutavel é diferente de mudar a variavel:"""

y = y + ' mundo'

y

"""Partindo dessas definições, dizemos que um objeto é mutável se ele (o objeto) puder ser mudado de qualquer maneira. Da mesma forma, dizemos que o objeto é imutável se ele não suporta nenhum tipo de operação ou função que o mude.



> **Por exemplo:**
Tanto strings quanto <font color = "orange"><b>`tuplas`</font></b> são <font color = "orange"><b>`types`</b></font> imutáveis (e, assim, não podemos modificar nem <font color = "orange"><b>`strings`</font></b>, nem <font color = "orange"><b>`tuplas`</font></b>), e por serem ambas comumente usadas repetidamente, Python salva na memória automaticamente como **aliases** (ou seja, se existe uma mesma <font color = "orange"><b>`string`</font></b>/<font color = "orange"><b>`tupla`</font></b> atribuída a diferentes variáveis, Python entende que essas variáveis são a mesma coisa). Já listas, por serem mutáveis, não suportam esse tipo de **aliasing**.

Sabemos que <font color = "orange"><b>`strings`</font></b> e <font color = "orange"><b>`tuplas`</font></b> são imutáveis, então nenhuma dos operadores ou funções que eleas suportam teriam algum efeito colateral no objeto em si (a função pode até imprimir algo diferente, mas o objeto não é alterado por isso).

Vamos ver:
"""

a = 'hello'

print(a.index('e'))
print(a)

print(a.upper())
print(a)

a = a.upper()  # Perceba que a string 'hello' não foi alterada.
a              #O que aconteceu é que uma nova string (a.upper()) foi atribuída à variável a

"""A primeira função, <font color = "orange"><b>`index()`</font></b>, faz sentido - nós não esperávamos que mudasse a string já que estamos só encontrando um de seus elementos, e não mudando ele. Mas e a <font color = "orange"><b>`upper()`</font></b>?

Na verdade, <font color = "orange"><b>`upper()`</font></b> não mudou a string. A <font color = "orange"><b>`upper()`</font></b> `hello` ainda existe e se mantém inalterada. O que mudou é o valor atribuído a variável `a`, que agora é <font color = "orange"><b>`a.upper()`</font></b>, ou seja, <font color = "orange"><b>`'hello'.upper()`</font></b>. Dizemos que **`a`** foi sobrescrito.

Esse é um padrão que vai aparecer com frequência - quando os objetos são imutáveis, eles têm esse tipo de  ***factory functions*** (ou ***creators***), que retornam novos objetos em vez de modificar o original.

Agora, vamos entender melhor sobre as listas. Como sabemos que elas são mutáveis, podemos esperar que algumas funções tenham "efeitos colaterais".
"""

b = ['x', 'y', 'z']
print(b.count('y'))
print(b)
print(b.reverse())
print(b)

"""Novamente, como o esperado, a função <font color = "orange"><b>`count()`</font></b> não mudou a lista, mas a função <font color = "orange"><b>`reverse()`</font></b> sim, então podemos dizer que um "efeito colateral" desta função é modificar a lista `b`. É a mesma coisa que vimos com o comando <font color = "orange"><b>`append()`</font></b>: o comando é do tipo **`None`**, então ele não tem nenhuma saída direta, apenas altera uma lista."""

x = [1, 2, 3]
x = x.append(4)
print(x)

x = [1, 2, 3]
x.append(4)
print(x)

"""Perceba nos próximos exemplos uma grande diferença entre** modificar uma variável** e** atualizar uma variável**:** Quando modificamos uma variável ela continua ocupando o mesmo local na memória** (tem o mesmo **`id`**), mas** quando sobrescrevemos a variável ela passa a ocupar um novo local na memória** (recebe um novo **`id`**)

Esse conceito vai ser útil um pouco à frente quando estivermos tratando sobre escopo.
"""

a = [1, 2, 3]
print(id(a), a)
a.append(4)
print(id(a), a)

b = [1, 2, 3]
print(id(b), b)
b = [1, 2, 3, 4]
print(id(b), b)

"""# 🔡 Variáveis Locais

Vamos ver agora um conceito ao qual chamamos de varíaveis locais, que está ligando principalmente à criação de funções.

Quando criamos uma função, podemos utilizar valores de variáveis que já foram definidas anteriormente, fora da função, ou podemos definir novas variáveis dentro da nossa função.

O que não é intuitivo é que **quando criamos variaves dentro de funções, estas variáveis existem somente dentro da função.** Isto é o que chamamos de **variáveis locais**. Se tentarmos usar váriaveis locais fora da função em que foram criadas nosso código não vai funcionar.
"""

def funcao(x):
    squared = x**2  #Aqui estamos criando uma variável local squared
    print(squared) #O comando print faz parte da função então a variável será mostrada sem problemas

x = 2
funcao(x)

print(squared) #A variavél squared não existe fora da função, pois é uma variável local;
         #Quando tentamos chamar ela fora da funçao que foi criada encontramos um erro.

"""Outra caracteristica das váriaveis locais, que inclusive pode ser mais "perigosa" é a de **atualização de valores por meio das variáveis locais**. Este erro pode acontecer quando, dentro de uma função, atribuímos um novo valor à uma variável já existente.

Variáveis criadas dentro de funções não podem ser utilizadas fora delas (logo vamos ver um comando que nos deixa fazer isso, mas esquece isso por enquanto...) mas o contrário não é verdade.

Podemos utilizar váriaveis ja definida anteriormente dentro de funções, e inclusive alterar seus valores, mas **após "sairmos" da função estas variáveis voltam a ter seus valores anteriores**, não sendo atualizados.

"""

squared = 2    #Inicialmente atribuímos o valor 2 à variável y
print(squared) #Aqui estamos printando o valor inicial de y, que é 2
funcao(squared)#Utilizamos o valor que já temos de y para chamar a função. Dentro dela, a variavel y recebe um novo valor igual a 4
print(squared) #Printamos novamente y, que deveria ter sido atualizada para 4, mas perceba que a variável contnua com seu valor inicial
         #Isto ocorre pois a variável y foi "atualizada localmente" dentro da função apenas; fora dela seu valor contínua sendo o inicial

"""Aí que está o grande perigo de erros como este: nossa variável não vai ser atualizada, mas o código continuará sendo executado. Ou seja,** o código vai ser executado com um valor errado sem nenhum tipo de aviso sobre isso**, e, se não percebermos isto, teremos uma resposta mesmo assim. Resumindo: **O código não apresentará nenhum tipo de erro, mas nossa resposta estará errada!**

***
 <font color = "grey">   **Erro Semântico X Erro Sintático**

  Vamos aproveitar o momento para discutir um pouco sobre a diferença entre erros semanticos e sintáticos.
  
  Este erro que acabamos de descrever é o **Erro Semântico**. Dizemos que um erro é do tipo semântico quando o código que escrevemos **pode ser executado**, mas por alguma razão ele **retorna um resultado diferente do experado** (como no exemplo anterior).

**Erros Sintáticos** são aqueles erros mais clássicos e em geral mais comuns, quando o código que escrevemos realmente** não roda** e aquela **mensagem de erro** gigante aparece no lugar da resposta. Isto acontece porque esse tipo de erro acontece justamente quando escrevemos alguma coisa que a linguagem não entende (por exemplo quando utilizamos uma variável que não foi definida anteriormente, utilizamos comandos ou funções que não exitem em python, ou ainda quando esquecemos do colocar os dois pontos no final do `if`)
  
 ***

Para evitar estes erros semânticos, para que uma variável criada ou atualizada localmente tenha seu valor atualizado tambem fora de sua função podemos utilizar o comando <font color = "orange"><b>`global y`</font></b>. Se ecrevermos isto dentro da função, antes de criar ou atualizar nossa variável, no caso chamamos ela de y, seu valor será utilizado tambem fora da função.
"""

def funcao2(x):
    global y
    y = x**2
    print(y)

y = 2
print(y)
funcao2(y)
print(y)

"""# 📌 Explorando o escopo

Agora que nós entendemos referências e os conceitos de **aliasing** e **mutabilidade**, vamos adicionar mais um elemento para, então, podemos juntar tudo.

Tenha certeza de que você está confortável com o conceito de variáveis locais, pois vamos utilizar o mesmo conceito de variáveis locais dentro de funções. A ideia é percebermos se essas variáveis são referências ou valores.

Vamos lá:
"""

def foo(x):
    print('point 2:', id(x))
    x = [1, 2, 3]
    print('point 3:', id(x))

L = [1, 2, 3]
print('point 1:', id(L))
foo(L)
print('point 4:', id(L))

"""---
####Explicando o exemplo acima:
Criamos uma lista L e pedimos que o código nos retorne seu **id**. Após isto, usamos esta lista que acabamos de criar como input para nossa função <font color = "orange"><b>`foo(x)`</font></b>.

Dentro do escopo da função, pedimos agora o **id** da variável X (que no caso é a lista L). Após isto, atribuimos à ela um novo valor, uma lista com elementos identicos à lista L inicial, e mostramos seu novo **id**

Por fim, saímos do escopo da função e mostamos novamente a o **id** da lista L.

---


Como podemos perceber, quando a lista L é passada para dentro da função <font color = "orange"><b>`foo(x)`</font></b> a variável local X é a mesma lista que a lista L, e refere-se ao mesmo objeto (como vimos quando estavamos comentando sobre *alias*)


Então, de início, a lista dentro da função ocupa o mesmo lugar na memória que a lista L inicial, pois são o mesmo objeto. Quando atualizamos a lista dentro da função, estamos criando um outro local em memória para armazená-la.

Mas se você entendeu o conceito de variáveis locais, deve ter percebido que atualizamos a lista L dentro de uma função, então apenas atualizamos uma variável local. Depois de sairmos do escopo da função, a lista L "volta a ser" a mesma lista que no início, inclusive referenciando o mesmo **id**.

---

Temos ainda uma peculiaridade dentro deste conceito de escopo quando utilizamos de funções que alteram objetos. Para entender essa peculiaridade precisamos lembrar do conceito de mutabilidade.

Como vimos lá atrás, na parte que trata de mutabilidade, quando utlizamos **funções que alteram um objeto** (como o comando <font color = "orange"><b>`append()`</font></b>), ele continua ocupando o mesmo local na memória. Apenas o valor do objeto que é atualizado, como podemos ver no exemplo a seguir:
"""

L=[1,2,3]
print(id(L), L)
L.append(4)
print(id(L), L)

"""O que acontece quando utilizamos váriaveis deste tipo dentro do escopo de uma função é que nossa variável, mesmo sendo atualizada localmente, continua com o valor atualizado fora do escopo da função. Isto porque o comando <font color = "orange"><b>`append()`</font></b> atualiza a variável mantendo seu **id**, ou seja, atualiza o mesmo local na memória.


Note que no próximo exemplo, diferente do exemplo anterior, o **id** da lista L fora e dentro da função é o mesmo nas 4 vezes, mas seu valor muda nas duas últimas.
"""

def foo(x):
    print('point 2:',id(x), x)
    x.append(4)
    print('point 3:', id(x), x)

L = [1, 2, 3]
print('point 1:', id(L), L)
foo(L)
print('point 4:', id(L), L)
